### ISSUE TITLE
?? Matic ?? Left

### ISSUE THREAD

**Issue by cblanquera** [gentlyawesome/liliannaroll-nft#2]
![image](https://user-images.githubusercontent.com/120378/150661372-ee31f6ad-95ff-4a28-bdc8-36081ed6ff66.png)
 
On page load I still see:

?? Matic ?? Left

Was expecting for the prices and quantity to load.

**Comment by cblanquera** [comment]
to clarify this is when my wallet is not connected

**Comment by gentlyawesome** [comment]
Let me check on this again

**Comment by gentlyawesome** [comment]
I just pushed an update on this. Kindly check in 5min, also altered some functions.

**Comment by cblanquera** [comment]
still the same thing. https://www.awesomescreenshot.com/video/6987494?key=3734dfeab2561a2738799fbe332890c7

**Comment by gentlyawesome** [comment]
For now I added some default and will change accordingly when the wallet is connected.

**Comment by cblanquera** [comment]
works now thanks
